services:
  postgres:
    container_name: radiance-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: radiance
    ports:
      - '5432:5432'
    volumes:
      - ../data/volumes/radiance:/var/lib/postgresql/data2
  radiance:
    build:
      context: .
    command: ['node', 'dist/main']
    env_file:
      - .env
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - postgres
